version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: "recommend-project"
    DOCKER_TAG: "latest"

phases:
  install:
    runtime-versions:
      python: 3.9  # Set the Python version required for the project
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # Install Python dependencies from requirements.txt

  pre_build:
    commands:
      - echo "Running tests..."
      # Optionally, run tests before building. Uncomment below line to run tests.
      # - pytest tests/
      - echo "Preparing for Docker image build..."

  build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo Amahesh4775 | docker login -u 45628 --password-stdin docker.io  # Login to Docker registry
      - echo "Building Docker image..."
      - docker build -t docker.io/45628/recommend-project:latest .  # Build Docker image using the Dockerfile
      - echo "Pushing Docker image to registry..."
      - docker push docker.io/45628/recommend-project:latest  # Push the image to the Docker registry

  post_build:
    commands:
      - echo "Build completed successfully!"  # Post build message, for logging purposes

artifacts:
  files:
    - '**/*'  # Include all files in the artifacts
  base-directory: .  # Set base directory from which to include the files
