version: '3'

services:
  web:
    image: "45628/recommend-project:latest"
    volumes:
      - "./db_data:/app/db_data"                 # Mount database directory
      - "./media/product_images:/app/mediafiles"  # Mount media files directory
      - "./django_cache:/app/cache_data" 
      - "./static:/app/static"         
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "recommend_project.wsgi:application"]
    ports:
      - "8000:8000"

volumes:
  db_data:
  django_cache:
